### ISSUE TITLE
Set remote to local mount for shared volume

### ISSUE THREAD

**Issue by Hybrid512** [HybridDevTools/d3nver#2]
Would be great to have something like this in the `config.yml` file :

```yaml
userinfo:
  ...
  mountpoint:
    path: '/media/j.doe/d3nver'
    type: 'nfs'
  ...
```

With this, `denver start` would :

* create the folder in path if needed
* mount the shared volume to this mount point

if there is no mountpoint defined in the configuration file, then just skip that part.

:warning: This will need privileges escalation which means `sudo` on Mac/Linux and who knows (UAC?) on Windows.
